---
-
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:
    -
      include_vars: vars/vpc_setup
      name: "Import VPC variables"
    -
      ec2_vpc_net:
        cidr_block: "{{vpcCidr}}"
        dns_hostname: true
        dns_support: true
        name: "{{vpc_name}}"
        state: "{{state}}"
        tenancy: default
      name: "Create vprofile VPC"
      register: vpcout
    -
      debug:
        var: vpcout
    -
      ec2_vpc_subnet:
        az: "{{ zone1 }}"
        cidr: "{{ PubSub1Cidr }}"
        map_public: true
        region: "{{ region }}"
        resource_tags:
          Name: vprofile-pubsub1
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
      name: "Create public subnet 1 in Zone 1"
      register: pubsub1_out
    -
      ec2_vpc_subnet:
        az: "{{ zone2 }}"
        cidr: "{{ PubSub2Cidr }}"
        map_public: true
        region: "{{ region }}"
        resource_tags:
          Name: vprofile-pubsub2
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
      name: "Create public subnet 2 in Zone 2"
      register: pubsub2_out
    -
      ec2_vpc_subnet:
        az: "{{ zone3 }}"
        cidr: "{{ PubSub3Cidr }}"
        map_public: true
        region: "{{ region }}"
        resource_tags:
          Name: vprofile-pubsub3
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
      name: "Create public subnet 3 in Zone 3"
      register: pubsub3_out
    -
      ec2_vpc_subnet:
        az: "{{ zone1 }}"
        cidr: "{{ PrivSub1Cidr }}"
        map_public: true
        region: "{{ region }}"
        resource_tags:
          Name: vprofile-privsub1
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
      name: "Create private subnet 1 in Zone 1"
      register: privsub1_out
    -
      ec2_vpc_subnet:
        az: "{{ zone2 }}"
        cidr: "{{ PrivSub2Cidr }}"
        map_public: true
        region: "{{ region }}"
        resource_tags:
          Name: vprofile-privsub2
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
      name: "Create private subnet 2 in Zone 2"
      register: privsub2_out
    -
      ec2_vpc_subnet:
        az: "{{ zone3 }}"
        cidr: "{{ PrivSub3Cidr }}"
        map_public: true
        region: "{{ region }}"
        resource_tags:
          Name: vprofile-privsub3
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
      name: "Create private subnet 3 in Zone 3"
      register: privsub3_out
    -
      ec2_vpc_igw:
        region: "{{ region }}"
        resource_tags:
          Name: vprofile-IGW
        state: "{{state}}"
        vpc_id: "{{ vpcout.vpc.id}}"
      name: "Internet Gateway Setup"
      register: igw_out
    -
      ec2_vpc_route_table:
        region: "{{ region }}"
        routes:
          -
            dest: 0.0.0.0/0
            gateway_id: "{{igw_out.gateway_id}}"
        subnets:
          - "{{pubsub1_out.subnet.id}}"
          - "{{pubsub2_out.subnet.id}}"
          - "{{pubsub3_out.subnet.id}}"
        tags:
          Name: VProfile-PubRT
        vpc_id: "{{vpcout.vpc.id}}"
      name: "Setup public subnet route table"
      register: pubRT_out
    -
      ec2_vpc_nat_gateway:
        if_exist_do_not_create: true
        region: "{{ region }}"
        state: "{{state}}"
        subnet_id: "{{ pubsub1_out.subnet.id }}"
        wait: true
      name: "Create NAT gateway and allocate new EIP if a nat gateway does not yet exist"
      register: NATGW_out
    -
      ec2_vpc_route_table:
        region: "{{ region }}"
        routes:
          -
            dest: 0.0.0.0/0
            gateway_id: "{{NATGW_out.gateway_id}}"
        subnets:
          - "{{privsub1_out.subnet.id}}"
          - "{{privsub2_out.subnet.id}}"
          - "{{privsub3_out.subnet.id}}"
        tags:
          Name: VProfile-PrivRT
        vpc_id: "{{vpcout.vpc.id}}"
      name: "Setup private subnet route table"
      register: privRT_out
    -
      debug:
        var: "{{item}}"
      loop:
        - vpcout.vpc.id
        - pubsub1_out.subnet.id
        - pubsub2_out.subnet.id
        - pubsub3_out.subnet.id
        - privsub1_out.subnet.id
        - privsub2_out.subnet.id
        - privsub3_out.subnet.id
        - igw_out.gateway_id
        - pubRT_out.route_table.id
        - NATGW_out.nat_gateway_id
        - privRT_out.route_table.id
    -
      set_fact:
        NATGWid: "{{NATGW_out.nat_gateway_id}}"
        cacheable: true
        igwid: "{{igw_out.gateway_id}}"
        privRTid: "{{privRT_out.route_table.id}}"
        privsub1id: "{{privsub1_out.subnet.id}}"
        privsub2id: "{{privsub2_out.subnet.id}}"
        privsub3id: "{{privsub3_out.subnet.id}}"
        pubRTid: "{{pubRT_out.route_table.id}}"
        pubsub1id: "{{pubsub1_out.subnet.id}}"
        pubsub2id: "{{pubsub2_out.subnet.id}}"
        pubub3id: "{{pubsub3_out.subnet.id}}"
        vpcid: "{{vpcout.vpc.id}}"
    -
      copy:
        content:
            vpcid: {{vpcout.vpc.id}}
            pubsub1id: {{pubsub1_out.subnet.id}}
            pubsub2id: {{pubsub2_out.subnet.id}}
            pubub3id: {{pubsub3_out.subnet.id}}
            privsub1id: {{privsub1_out.subnet.id}}
            privsub2id: {{privsub2_out.subnet.id}}
            privsub3id: {{privsub3_out.subnet.id}}
            igwid: {{igw_out.gateway_id}}
            pubRTid: {{pubRT_out.route_table.id}}
            NATGWid: {{NATGW_out.nat_gateway_id}}
            privRTid: {{privRT_out.route_table.id}}
        dest: vars/output_vars
      name: "Create variable file for vpc output"